<a href="https://colab.research.google.com/github/torcodex/Python-Practices/blob/main/PandasHandson3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data = { 'Order_ID': [ 501,502,503,504,505,506,507,508,509,510, 511,512,513,514,515,516,516 ],

'Customer': [
    'Rahul','Priya','Amit','Sneha','Arjun','Neha','Rohan',
    'Anjali','Vikas','Pooja','Karan','Meera',None,'Simran',
    'Nikhil','Isha','Isha'
],

'Restaurant': [
    'Burger House','Pizza Corner','Spice Hub','Burger House',
    'Pizza Corner','Food Factory','Spice Hub','Burger House',
    'Food Factory','Pizza Corner','Spice Hub','Food Factory',
    'Burger House','Pizza Corner','Food Factory','Spice Hub',
    'Spice Hub'
],

'City': [
    'Bangalore','Bangalore','Mumbai','Delhi','Mumbai','Delhi',
    'Bangalore','Mumbai','Delhi','Bangalore','Mumbai','Delhi',
    'Bangalore','Mumbai','Delhi','Bangalore','Bangalore'
],

'Order_Value': [
    450,800,650,300,1200,550,900,350,750,1100,
    500,950,400,700,1300,600,600
],

'Delivery_Time': [
    32,48,40,55,62,35,70,28,58,65,
    45,52,38,75,80,None,60
],

'Discount': [
    10,15,5,0,20,10,25,0,15,20,
    5,10,0,25,30,10,10
],

'Rating': [
    5,4,4,2,5,3,2,5,3,2,
    4,4,5,None,5,3,3
],

'Order_Status': [
    'Delivered','Delivered','Delivered','Cancelled',
    'Delivered','Delivered','Cancelled','Delivered',
    'Delivered','Cancelled','Delivered','Delivered',
    'Delivered','Cancelled','Delivered','Cancelled',
    'Cancelled'
],

'Payment_Mode': [
    'UPI','Card','UPI','Cash','Card','UPI','Card',
    'UPI','Cash','CARD','UPI','Card','UPI','card',
    'UPI','Cash','Cash'
]
}

df = pd.DataFrame(data)

df

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode
0,501,Rahul,Burger House,Bangalore,450,32.0,10,5.0,Delivered,UPI
1,502,Priya,Pizza Corner,Bangalore,800,48.0,15,4.0,Delivered,Card
2,503,Amit,Spice Hub,Mumbai,650,40.0,5,4.0,Delivered,UPI
3,504,Sneha,Burger House,Delhi,300,55.0,0,2.0,Cancelled,Cash
4,505,Arjun,Pizza Corner,Mumbai,1200,62.0,20,5.0,Delivered,Card
5,506,Neha,Food Factory,Delhi,550,35.0,10,3.0,Delivered,UPI
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,Card
7,508,Anjali,Burger House,Mumbai,350,28.0,0,5.0,Delivered,UPI
8,509,Vikas,Food Factory,Delhi,750,58.0,15,3.0,Delivered,Cash
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD
10,511,Karan,Spice Hub,Mumbai,500,45.0,5,4.0,Delivered,UPI
11,512,Meera,Food Factory,Delhi,950,52.0,10,4.0,Delivered,Card
12,513,None,Burger House,Bangalore,400,38.0,0,5.0,Delivered,UPI
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,NaN,Cancelled,card
14,515,Nikhil,Food Factory,Delhi,1300,80.0,30,5.0,Delivered,UPI
15,516,Isha,Spice Hub,Bangalore,600,NaN,10,3.0,Cancelled,Cash
16,516,Isha,Spice Hub,Bangalore,600,60.0,10,3.0,Cancelled,Cash

In [ ]:
print(df.shape)
print(df.dtypes)

(17, 10)
Order_ID           int64
Customer          object
Restaurant        object
City              object
Order_Value        int64
Delivery_Time    float64
Discount           int64
Rating           float64
Order_Status      object
Payment_Mode      object
dtype: object

In [ ]:
df.isna().sum()

Order_ID         0
Customer         1
Restaurant       0
City             0
Order_Value      0
Delivery_Time    1
Discount         0
Rating           1
Order_Status     0
Payment_Mode     0
dtype: int64

In [ ]:
df['Order_ID'].duplicated().sum()

np.int64(1)

In [ ]:
df.drop_duplicates("Order_ID",keep="last",inplace=True)
df

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode
0,501,Rahul,Burger House,Bangalore,450,32.0,10,5.0,Delivered,UPI
1,502,Priya,Pizza Corner,Bangalore,800,48.0,15,4.0,Delivered,Card
2,503,Amit,Spice Hub,Mumbai,650,40.0,5,4.0,Delivered,UPI
3,504,Sneha,Burger House,Delhi,300,55.0,0,2.0,Cancelled,Cash
4,505,Arjun,Pizza Corner,Mumbai,1200,62.0,20,5.0,Delivered,Card
5,506,Neha,Food Factory,Delhi,550,35.0,10,3.0,Delivered,UPI
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,Card
7,508,Anjali,Burger House,Mumbai,350,28.0,0,5.0,Delivered,UPI
8,509,Vikas,Food Factory,Delhi,750,58.0,15,3.0,Delivered,Cash
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD
10,511,Karan,Spice Hub,Mumbai,500,45.0,5,4.0,Delivered,UPI
11,512,Meera,Food Factory,Delhi,950,52.0,10,4.0,Delivered,Card
12,513,None,Burger House,Bangalore,400,38.0,0,5.0,Delivered,UPI
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,NaN,Cancelled,card
14,515,Nikhil,Food Factory,Delhi,1300,80.0,30,5.0,Delivered,UPI
16,516,Isha,Spice Hub,Bangalore,600,60.0,10,3.0,Cancelled,Cash

In [ ]:
df['Customer'].fillna("Unknown",inplace=True)
df['Rating']=df['Rating'].fillna(df.groupby("Restaurant")["Rating"].transform("median"))
df

/tmp/ipykernel_342/4257307461.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer'].fillna("Unknown",inplace=True)

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode
0,501,Rahul,Burger House,Bangalore,450,32.0,10,5.0,Delivered,UPI
1,502,Priya,Pizza Corner,Bangalore,800,48.0,15,4.0,Delivered,Card
2,503,Amit,Spice Hub,Mumbai,650,40.0,5,4.0,Delivered,UPI
3,504,Sneha,Burger House,Delhi,300,55.0,0,2.0,Cancelled,Cash
4,505,Arjun,Pizza Corner,Mumbai,1200,62.0,20,5.0,Delivered,Card
5,506,Neha,Food Factory,Delhi,550,35.0,10,3.0,Delivered,UPI
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,Card
7,508,Anjali,Burger House,Mumbai,350,28.0,0,5.0,Delivered,UPI
8,509,Vikas,Food Factory,Delhi,750,58.0,15,3.0,Delivered,Cash
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD
10,511,Karan,Spice Hub,Mumbai,500,45.0,5,4.0,Delivered,UPI
11,512,Meera,Food Factory,Delhi,950,52.0,10,4.0,Delivered,Card
12,513,Unknown,Burger House,Bangalore,400,38.0,0,5.0,Delivered,UPI
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,4.0,Cancelled,card
14,515,Nikhil,Food Factory,Delhi,1300,80.0,30,5.0,Delivered,UPI
16,516,Isha,Spice Hub,Bangalore,600,60.0,10,3.0,Cancelled,Cash

In [ ]:
df['Payment_Mode'] = df['Payment_Mode'].str.upper()
df

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode
0,501,Rahul,Burger House,Bangalore,450,32.0,10,5.0,Delivered,UPI
1,502,Priya,Pizza Corner,Bangalore,800,48.0,15,4.0,Delivered,CARD
2,503,Amit,Spice Hub,Mumbai,650,40.0,5,4.0,Delivered,UPI
3,504,Sneha,Burger House,Delhi,300,55.0,0,2.0,Cancelled,CASH
4,505,Arjun,Pizza Corner,Mumbai,1200,62.0,20,5.0,Delivered,CARD
5,506,Neha,Food Factory,Delhi,550,35.0,10,3.0,Delivered,UPI
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,CARD
7,508,Anjali,Burger House,Mumbai,350,28.0,0,5.0,Delivered,UPI
8,509,Vikas,Food Factory,Delhi,750,58.0,15,3.0,Delivered,CASH
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD
10,511,Karan,Spice Hub,Mumbai,500,45.0,5,4.0,Delivered,UPI
11,512,Meera,Food Factory,Delhi,950,52.0,10,4.0,Delivered,CARD
12,513,Unknown,Burger House,Bangalore,400,38.0,0,5.0,Delivered,UPI
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,4.0,Cancelled,CARD
14,515,Nikhil,Food Factory,Delhi,1300,80.0,30,5.0,Delivered,UPI
16,516,Isha,Spice Hub,Bangalore,600,60.0,10,3.0,Cancelled,CASH

In [ ]:
df['Payment_Mode'].unique()

array(['UPI', 'CARD', 'CASH'], dtype=object)

In [ ]:
df['Discount_Amount'] = df["Order_Value"]*(df['Discount']/100)

In [ ]:
df['Final_Order_Value'] = df['Order_Value'] - df['Discount_Amount']

In [ ]:
def typing(a):
    if(a<=40):
        return "Fast"
    elif(a<=60):
        return 'Normal'
    else:
        return 'Slow'
df['Delivery_Performance'] = df['Delivery_Time'].apply(typing)

In [ ]:
df['Delivery_Performance'].groupby(df['Delivery_Performance']).count()

Delivery_Performance
Fast      5
Normal    6
Slow      5
Name: Delivery_Performance, dtype: int64

In [ ]:
df.groupby('Restaurant')['Delivery_Time'].mean()

Restaurant
Burger House    38.25
Food Factory    56.25
Pizza Corner    62.50
Spice Hub       53.75
Name: Delivery_Time, dtype: float64

In [ ]:
avgs = df.groupby('Restaurant')['Delivery_Time'].mean()
avgs[avgs>50]

Restaurant
Food Factory    56.25
Pizza Corner    62.50
Spice Hub       53.75
Name: Delivery_Time, dtype: float64

In [ ]:
df[(df['Delivery_Time']>60) & (df['Order_Status']=='Cancelled')]

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode,Discount_Amount,Final_Order_Value,Delivery_Performance
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,CARD,225.0,675.0,Slow
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD,220.0,880.0,Slow
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,4.0,Cancelled,CARD,175.0,525.0,Slow

In [ ]:
c = df[df['Order_Status']=='Cancelled']['Order_Status'].count()
tots = df['Order_Status'].count()
print((c/tots)*100)

31.25

In [ ]:
df[(df['Delivery_Time']>60) & (df['Rating']<=3)]

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode,Discount_Amount,Final_Order_Value,Delivery_Performance
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,CARD,225.0,675.0,Slow
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD,220.0,880.0,Slow

In [ ]:
df.groupby('Restaurant')['Rating'].mean()

Restaurant
Burger House    4.25
Food Factory    3.75
Pizza Corner    3.75
Spice Hub       3.25
Name: Rating, dtype: float64

In [ ]:
ratings = df.groupby('Restaurant')['Rating'].mean()
ratings[ratings<4]

Restaurant
Food Factory    3.75
Pizza Corner    3.75
Spice Hub       3.25
Name: Rating, dtype: float64

In [ ]:
df[df['Order_Status']=='Delivered'].groupby('Delivery_Performance')['Rating'].mean()

Delivery_Performance
Fast      4.40
Normal    3.75
Slow      5.00
Name: Rating, dtype: float64

In [ ]:
df.groupby('Restaurant')['Discount'].mean()

Restaurant
Burger House     2.50
Food Factory    16.25
Pizza Corner    20.00
Spice Hub       11.25
Name: Discount, dtype: float64

In [ ]:
df[df['Discount']>=20]

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode,Discount_Amount,Final_Order_Value,Delivery_Performance
4,505,Arjun,Pizza Corner,Mumbai,1200,62.0,20,5.0,Delivered,CARD,240.0,960.0,Slow
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,CARD,225.0,675.0,Slow
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD,220.0,880.0,Slow
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,4.0,Cancelled,CARD,175.0,525.0,Slow
14,515,Nikhil,Food Factory,Delhi,1300,80.0,30,5.0,Delivered,UPI,390.0,910.0,Slow

In [ ]:
df[df['Discount']>=20]['Final_Order_Value'].mean()

np.float64(790.0)

In [ ]:
df[df['Discount']<20]['Final_Order_Value'].mean()

np.float64(523.1818181818181)

In [ ]:
df.groupby((df['Discount']>=20).map({True:"Discount >= 20%", False:"Discount < 20%"}))['Final_Order_Value'].mean()

Discount
Discount < 20%     523.181818
Discount >= 20%    790.000000
Name: Final_Order_Value, dtype: float64

In [ ]:
df.groupby('Restaurant')['Discount_Amount'].max().sort_values(ascending=False).head(1)

Restaurant
Food Factory    390.0
Name: Discount_Amount, dtype: float64

In [ ]:
df.groupby('Restaurant')['Order_ID'].count()

Restaurant
Burger House    4
Food Factory    4
Pizza Corner    4
Spice Hub       4
Name: Order_ID, dtype: int64

In [ ]:
df['Delivered_Orders'] = np.where(df['Order_Status']=='Delivered',1,0)

df['Cancelled_Orders'] = np.where(df['Order_Status']=='Cancelled',1,0)

In [ ]:
df

,Order_ID,Customer,Restaurant,City,Order_Value,Delivery_Time,Discount,Rating,Order_Status,Payment_Mode,Discount_Amount,Final_Order_Value,Delivery_Performance,Delivered_Orders,Cancelled_Orders
0,501,Rahul,Burger House,Bangalore,450,32.0,10,5.0,Delivered,UPI,45.0,405.0,Fast,1,0
1,502,Priya,Pizza Corner,Bangalore,800,48.0,15,4.0,Delivered,CARD,120.0,680.0,Normal,1,0
2,503,Amit,Spice Hub,Mumbai,650,40.0,5,4.0,Delivered,UPI,32.5,617.5,Fast,1,0
3,504,Sneha,Burger House,Delhi,300,55.0,0,2.0,Cancelled,CASH,0.0,300.0,Normal,0,1
4,505,Arjun,Pizza Corner,Mumbai,1200,62.0,20,5.0,Delivered,CARD,240.0,960.0,Slow,1,0
5,506,Neha,Food Factory,Delhi,550,35.0,10,3.0,Delivered,UPI,55.0,495.0,Fast,1,0
6,507,Rohan,Spice Hub,Bangalore,900,70.0,25,2.0,Cancelled,CARD,225.0,675.0,Slow,0,1
7,508,Anjali,Burger House,Mumbai,350,28.0,0,5.0,Delivered,UPI,0.0,350.0,Fast,1,0
8,509,Vikas,Food Factory,Delhi,750,58.0,15,3.0,Delivered,CASH,112.5,637.5,Normal,1,0
9,510,Pooja,Pizza Corner,Bangalore,1100,65.0,20,2.0,Cancelled,CARD,220.0,880.0,Slow,0,1
10,511,Karan,Spice Hub,Mumbai,500,45.0,5,4.0,Delivered,UPI,25.0,475.0,Normal,1,0
11,512,Meera,Food Factory,Delhi,950,52.0,10,4.0,Delivered,CARD,95.0,855.0,Normal,1,0
12,513,Unknown,Burger House,Bangalore,400,38.0,0,5.0,Delivered,UPI,0.0,400.0,Fast,1,0
13,514,Simran,Pizza Corner,Mumbai,700,75.0,25,4.0,Cancelled,CARD,175.0,525.0,Slow,0,1
14,515,Nikhil,Food Factory,Delhi,1300,80.0,30,5.0,Delivered,UPI,390.0,910.0,Slow,1,0
16,516,Isha,Spice Hub,Bangalore,600,60.0,10,3.0,Cancelled,CASH,60.0,540.0,Normal,0,1

In [ ]:
Restaurant_Summary = df.groupby('Restaurant').agg(
    Total_Orders = ('Order_ID',"count"),
    Delivered_Orders = ('Delivered_Orders','sum'),
    Cancelled_Orders = ('Cancelled_Orders', 'sum'),
    Average_Order_Value = ('Order_Value','mean'),
    Average_Delivery_Time = ('Delivery_Time','mean'),
    Average_Rating = ('Rating','mean'),
    Total_Revenue = ('Final_Order_Value','sum')
)

Restaurant_Summary['Cancellation_Rate'] = (Restaurant_Summary['Cancelled_Orders']/Restaurant_Summary['Total_Orders'] *100).astype(int)

In [ ]:
Restaurant_Summary

,Total_Orders,Delivered_Orders,Cancelled_Orders,Average_Order_Value,Average_Delivery_Time,Average_Rating,Total_Revenue,Cancellation_Rate
Restaurant,,,,,,,,
Burger House,4,3,1,375.0,38.25,4.25,1455.0,25
Food Factory,4,4,0,887.5,56.25,3.75,2897.5,0
Pizza Corner,4,2,2,950.0,62.50,3.75,3045.0,50
Spice Hub,4,2,2,662.5,53.75,3.25,2307.5,50

In [ ]:
Restaurant_Summary[Restaurant_Summary['Cancellation_Rate']>20]

,Total_Orders,Delivered_Orders,Cancelled_Orders,Average_Order_Value,Average_Delivery_Time,Average_Rating,Total_Revenue,Cancellation_Rate
Restaurant,,,,,,,,
Burger House,4,3,1,375.0,38.25,4.25,1455.0,25
Pizza Corner,4,2,2,950.0,62.50,3.75,3045.0,50
Spice Hub,4,2,2,662.5,53.75,3.25,2307.5,50

In [ ]:
Restaurant_Summary = Restaurant_Summary.sort_values('Cancellation_Rate',ascending=False)

In [ ]:
Restaurant_Summary[
    (Restaurant_Summary['Cancellation_Rate']==Restaurant_Summary['Cancellation_Rate'].max())&
    (Restaurant_Summary['Average_Delivery_Time']==Restaurant_Summary['Average_Delivery_Time'].max())
]

,Total_Orders,Delivered_Orders,Cancelled_Orders,Average_Order_Value,Average_Delivery_Time,Average_Rating,Total_Revenue,Cancellation_Rate
Restaurant,,,,,,,,
Pizza Corner,4,2,2,950.0,62.5,3.75,3045.0,50

In [ ]:
df[(df['Delivery_Time']==df['Delivery_Time'].max()) & (df['Delivery_Performance']=='Fast')]

Empty DataFrame
Columns: [Order_ID, Customer, Restaurant, City, Order_Value, Delivery_Time, Discount, Rating, Order_Status, Payment_Mode, Discount_Amount, Final_Order_Value, Delivery_Performance, Delivered_Orders, Cancelled_Orders]
Index: []

In [ ]:
Restaurant_Summary[['Cancellation_Rate','Average_Delivery_Time']].sort_values(by=['Cancellation_Rate','Average_Delivery_Time'],ascending=False).head(1)

              Cancellation_Rate  Average_Delivery_Time
Restaurant
Pizza Corner                 50                   62.5

In [ ]:
Restaurant_Summary[['Average_Rating','Average_Delivery_Time']].sort_values(by=['Average_Rating','Average_Delivery_Time'],ascending=False).head(1)

              Average_Rating  Average_Delivery_Time
Restaurant
Burger House            4.25                  38.25

In [ ]:
df['Discount_Group'] = np.where(df['Discount']>=20,"Discount>=20","Discount<20")
asin = df.groupby('Discount_Group')['Final_Order_Value'].mean()
if asin.iloc[0] > asin.iloc[1]:
    print(f"Average Final Order Value: {asin.iloc[0]}\nOrders with Discount<20 is more profitable")
else:
    print(f"Average Final Order Value: {asin.iloc[1]}\nOrders with Discount>=20 is more profitable")

Average Final Order Value: 790.0
Orders with Discount>=20 is more profitable

In [ ]:
sums = df['Final_Order_Value'].groupby(df['Order_Status']).sum()
total_sum = sums.sum()
percent = (sums['Cancelled']/total_sum)*100
print(percent.round(1))

30.1

In [ ]:
cities = df.groupby(['Order_Status','City'])['Final_Order_Value'].mean()
cities['Delivered'].sort_values(ascending=False).head(1)

City
Delhi    724.375
Name: Final_Order_Value, dtype: float64

In [ ]:
dfs = df.groupby('Restaurant').agg(
    Total_Orders = ('Order_ID',"count"),
    Cancelled_Orders = ('Cancelled_Orders', 'sum'),
    Average_Delivery_Time = ('Delivery_Time','mean'),
    Average_Rating = ('Rating','mean'),
    Total_Revenue = ('Final_Order_Value','sum')
)

dfs['Cancellation_Rate'] = (dfs['Cancelled_Orders']/dfs['Total_Orders'] *100).astype(int)
dfs = dfs.sort_values('Cancellation_Rate',ascending=False)
dfs

,Total_Orders,Cancelled_Orders,Average_Delivery_Time,Average_Rating,Total_Revenue,Cancellation_Rate
Restaurant,,,,,,
Spice Hub,4,2,53.75,3.25,2307.5,50
Pizza Corner,4,2,62.50,3.75,3045.0,50
Burger House,4,1,38.25,4.25,1455.0,25
Food Factory,4,0,56.25,3.75,2897.5,0