<a href="https://colab.research.google.com/github/torcodex/Python-Practices/blob/main/PandasHandson4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [237]:
import pandas as pd
import numpy as np

data = {

    'Order_ID': [
        1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
        1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,
        1021,1022,1023,1024,1025,1026,1027,1028,1029,1030
    ],

    'Customer': [
        'Arun','Priya','Rahul','Sneha','Vikram','Anjali','Kiran',
        'Neha','Rohit','Pooja','Amit','Meera','Sanjay','Divya',
        'Nikhil','Isha','Varun','Asha','Rakesh','Anu',
        'Arun','Priya','Rahul','Sneha','Vikram','Kiran',
        'Neha','Rohit','Pooja','Amit'
    ],

    'City': [
        'Bangalore','Mumbai','Delhi','Chennai','Bangalore','Hyderabad',
        'Mumbai','Delhi','Bangalore','Chennai','Hyderabad','Mumbai',
        'Delhi','Bangalore','Chennai','Mumbai','Hyderabad','Delhi',
        'Bangalore','Chennai','Bangalore','Mumbai','Delhi','Chennai',
        'Bangalore','Mumbai','Delhi','Hyderabad','Chennai','Bangalore'
    ],

    'Product_Category': [
        'Electronics','Clothing','Electronics','Home Appliances',
        'Electronics','Clothing','Home Appliances','Electronics',
        'Clothing','Electronics','Home Appliances','Clothing',
        'Electronics','Home Appliances','Clothing','Electronics',
        'Home Appliances','Clothing','Electronics','Electronics',
        'Electronics','Clothing','Electronics','Home Appliances',
        'Electronics','Clothing','Home Appliances','Electronics',
        'Clothing','Electronics'
    ],

    'Product': [
        'Laptop','T-Shirt','Headphones','Mixer','Smartphone','Jeans',
        'Microwave','Tablet','Jacket','Smartwatch','Air Fryer',
        'Shoes','Laptop','Mixer','T-Shirt','Headphones','Microwave',
        'Jeans','Smartphone','Smartwatch','Laptop','Shoes',
        'Headphones','Microwave','Tablet','Jacket','Air Fryer',
        'Smartphone','Jeans','Laptop'
    ],

    'Quantity': [
        1,2,1,1,1,2,1,1,1,2,
        1,1,1,2,3,1,1,2,1,1,
        1,2,2,1,1,1,2,1,2,1
    ],

    'Unit_Price': [
        65000,1200,2500,4500,55000,2200,8500,30000,3500,8000,
        7000,4000,65000,4500,1200,2500,8500,2200,55000,8000,
        65000,4000,2500,8500,30000,3500,7000,55000,2200,65000
    ],

    'Discount': [
        10,20,5,15,10,25,5,20,30,10,
        15,5,20,10,25,15,10,20,5,30,
        10,25,15,5,20,30,10,15,25,10
    ],

    'Order_Date': [
        '2026-01-05','2026-01-07','2026-01-08','2026-01-10',
        '2026-01-12','2026-01-14','2026-01-15','2026-01-18',
        '2026-01-20','2026-01-22','2026-01-25','2026-01-27',
        '2026-02-01','2026-02-03','2026-02-05','2026-02-07',
        '2026-02-10','2026-02-12','2026-02-15','2026-02-18',
        '2026-02-20','2026-02-22','2026-02-25','2026-02-27',
        '2026-03-01','2026-03-03','2026-03-05','2026-03-07',
        '2026-03-10','2026-03-12'
    ],

    'Delivery_Days': [
        2,4,3,6,2,5,7,3,8,2,
        5,4,3,6,2,4,7,5,3,2,
        4,6,3,8,2,7,5,3,6,2
    ],

    'Rating': [
        5,4,4,2,5,3,2,5,3,4,
        4,3,5,2,5,4,3,4,5,3,
        5,2,4,3,5,2,4,5,3,5
    ],

    'Order_Status': [
        'Delivered','Delivered','Delivered','Cancelled',
        'Delivered','Delivered','Cancelled','Delivered',
        'Delivered','Cancelled','Delivered','Delivered',
        'Delivered','Cancelled','Delivered','Delivered',
        'Cancelled','Delivered','Delivered','Cancelled',
        'Delivered','Cancelled','Delivered','Delivered',
        'Delivered','Cancelled','Delivered','Delivered',
        'Cancelled','Delivered'
    ],

    'Payment_Mode': [
        'UPI','Card','UPI','Cash','CARD','UPI','card','UPI',
        'Cash','CARD','UPI','Card','UPI','card','Cash','UPI',
        'CARD','UPI','Card','Cash','UPI','card','UPI','Cash',
        'CARD','UPI','Card','UPI','cash','CARD'
    ],

    'Customer_Type': [
        'New','Returning','New','Returning','New','Returning',
        'New','Returning','New','Returning','New','Returning',
        'New','Returning','New','Returning','New','Returning',
        'New','Returning','Returning','New','Returning','New',
        'Returning','New','Returning','New','Returning','New'
    ]
}

df = pd.DataFrame(data)

df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,Card,Returning
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,Cash,Returning
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,card,New
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,Cash,New
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,Card,Returning
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,card,Returning
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,Cash,New
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,Card,New
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,Cash,Returning
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,card,New
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,Cash,New
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,Card,Returning
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,cash,Returning
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New

In [238]:
df.shape

(30, 14)

In [239]:
df.head(10)

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,Card,Returning
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,Cash,Returning
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,card,New
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,Cash,New
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning

In [240]:
df.tail(5)

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,Card,Returning
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,cash,Returning
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New

In [241]:
df.columns

Index(['Order_ID', 'Customer', 'City', 'Product_Category', 'Product',
       'Quantity', 'Unit_Price', 'Discount', 'Order_Date', 'Delivery_Days',
       'Rating', 'Order_Status', 'Payment_Mode', 'Customer_Type'],
      dtype='object')

In [242]:
df.dtypes

Order_ID             int64
Customer            object
City                object
Product_Category    object
Product             object
Quantity             int64
Unit_Price           int64
Discount             int64
Order_Date          object
Delivery_Days        int64
Rating               int64
Order_Status        object
Payment_Mode        object
Customer_Type       object
dtype: object

In [243]:
df.nunique()

Order_ID            30
Customer            20
City                 5
Product_Category     3
Product             12
Quantity             3
Unit_Price          12
Discount             6
Order_Date          30
Delivery_Days        7
Rating               4
Order_Status         2
Payment_Mode         6
Customer_Type        2
dtype: int64

In [244]:
df.describe()

,Order_ID,Quantity,Unit_Price,Discount,Delivery_Days,Rating
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,1015.500000,1.366667,19366.666667,15.666667,4.300000,3.766667
std,8.803408,0.556053,24282.011695,8.065821,1.950243,1.104328
min,1001.000000,1.000000,1200.000000,5.000000,2.000000,2.000000
25%,1008.250000,1.000000,2750.000000,10.000000,3.000000,3.000000
50%,1015.500000,1.000000,7000.000000,15.000000,4.000000,4.000000
75%,1022.750000,2.000000,30000.000000,20.000000,6.000000,5.000000
max,1030.000000,3.000000,65000.000000,30.000000,8.000000,5.000000

In [245]:
df.isna().sum()

Order_ID            0
Customer            0
City                0
Product_Category    0
Product             0
Quantity            0
Unit_Price          0
Discount            0
Order_Date          0
Delivery_Days       0
Rating              0
Order_Status        0
Payment_Mode        0
Customer_Type       0
dtype: int64

In [246]:
df['Order_ID'].duplicated().sum()

np.int64(0)

In [247]:
df.duplicated().sum()

np.int64(0)

In [248]:
df['Payment_Mode'] = df['Payment_Mode'].str.upper()
df['Payment_Mode']

0      UPI
1     CARD
2      UPI
3     CASH
4     CARD
5      UPI
6     CARD
7      UPI
8     CASH
9     CARD
10     UPI
11    CARD
12     UPI
13    CARD
14    CASH
15     UPI
16    CARD
17     UPI
18    CARD
19    CASH
20     UPI
21    CARD
22     UPI
23    CASH
24    CARD
25     UPI
26    CARD
27     UPI
28    CASH
29    CARD
Name: Payment_Mode, dtype: object

In [249]:
df['Payment_Mode'].unique()

array(['UPI', 'CARD', 'CASH'], dtype=object)

In [250]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Order_Date'].dtype

dtype('<M8[ns]')

In [251]:
df['Order_Value'] = df['Quantity'] * df['Unit_Price']
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000

In [252]:
df[df['Order_Value'] > 50]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000

In [253]:
df[df['Discount']>=20]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400

In [254]:
df[df['City']=='Bangalore']

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000

In [255]:
df[df['City']=='Mumbai']

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500

In [256]:
df[df['Rating']<=3]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400

In [257]:
df[df['Order_Status']=='Cancelled']

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400

In [258]:
df[df['Order_Status']=='Delivered']

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000

In [259]:
df[df['Delivery_Days']>5]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400

In [260]:
df[(df['Discount']>=20) & (df['Rating']<=3)]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400

In [261]:
df[(df['Order_Status']=='Delivered')&(df['Delivery_Days']<=5)]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000

In [262]:
df[(df['Order_Status']=='Delivered')&(df['City']=='Bangalore')]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000

In [263]:
df['Discount_Amount'] = df['Order_Value'] * (df['Discount']/100)
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000,6500.0
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400,480.0
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500,125.0
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000,5500.0
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400,1100.0
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000,6000.0
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500,1050.0
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000,1600.0
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000,1050.0
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000,200.0
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000,13000.0
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600,900.0
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500,375.0
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400,880.0
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000,2750.0
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000,2400.0
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000,6500.0
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000,750.0
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500,425.0
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000,6000.0
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000,1400.0
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000,8250.0
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000,6500.0

In [264]:
df['Final_Order_Value'] = df['Order_Value'] - df['Discount_Amount']
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000,6500.0,58500.0
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400,480.0,1920.0
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500,125.0,2375.0
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0,3825.0
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000,5500.0,49500.0
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400,1100.0,3300.0
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0,8075.0
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000,6000.0,24000.0
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500,1050.0,2450.0
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000,1600.0,14400.0
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000,1050.0,5950.0
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000,200.0,3800.0
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000,13000.0,52000.0
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0,8100.0
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600,900.0,2700.0
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500,375.0,2125.0
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0,7650.0
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400,880.0,3520.0
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000,2750.0,52250.0
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000,2400.0,5600.0
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000,6500.0,58500.0
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0,6000.0
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000,750.0,4250.0
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500,425.0,8075.0
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000,6000.0,24000.0
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0,2450.0
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000,1400.0,12600.0
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000,8250.0,46750.0
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0,3300.0
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000,6500.0,58500.0

In [265]:
df['Delivery_Performance'] = df['Delivery_Days'].apply(lambda x: 'Fast' if x<=3 else 'Normal' if x<=5 else 'Slow')
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000,6500.0,58500.0,Fast
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400,480.0,1920.0,Normal
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500,125.0,2375.0,Fast
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0,3825.0,Slow
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000,5500.0,49500.0,Fast
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400,1100.0,3300.0,Normal
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0,8075.0,Slow
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000,6000.0,24000.0,Fast
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500,1050.0,2450.0,Slow
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000,1600.0,14400.0,Fast
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000,1050.0,5950.0,Normal
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000,200.0,3800.0,Normal
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000,13000.0,52000.0,Fast
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0,8100.0,Slow
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600,900.0,2700.0,Fast
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500,375.0,2125.0,Normal
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0,7650.0,Slow
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400,880.0,3520.0,Normal
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000,2750.0,52250.0,Fast
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000,2400.0,5600.0,Fast
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000,6500.0,58500.0,Normal
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0,6000.0,Slow
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000,750.0,4250.0,Fast
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500,425.0,8075.0,Slow
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000,6000.0,24000.0,Fast
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0,2450.0,Slow
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000,1400.0,12600.0,Normal
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000,8250.0,46750.0,Fast
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0,3300.0,Slow
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000,6500.0,58500.0,Fast

In [266]:
df['Discount_Category'] = df['Discount'].apply(
    lambda x: 'High' if x>20 else 'Medium' if x>10 else 'Low'
)
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000,6500.0,58500.0,Fast,Low
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400,480.0,1920.0,Normal,Medium
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500,125.0,2375.0,Fast,Low
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0,3825.0,Slow,Medium
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000,5500.0,49500.0,Fast,Low
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400,1100.0,3300.0,Normal,High
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0,8075.0,Slow,Low
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000,6000.0,24000.0,Fast,Medium
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500,1050.0,2450.0,Slow,High
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000,1600.0,14400.0,Fast,Low
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000,1050.0,5950.0,Normal,Medium
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000,200.0,3800.0,Normal,Low
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000,13000.0,52000.0,Fast,Medium
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0,8100.0,Slow,Low
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600,900.0,2700.0,Fast,High
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500,375.0,2125.0,Normal,Medium
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0,7650.0,Slow,Low
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400,880.0,3520.0,Normal,Medium
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000,2750.0,52250.0,Fast,Low
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000,2400.0,5600.0,Fast,High
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000,6500.0,58500.0,Normal,Low
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0,6000.0,Slow,High
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000,750.0,4250.0,Fast,Medium
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500,425.0,8075.0,Slow,Low
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000,6000.0,24000.0,Fast,Medium
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0,2450.0,Slow,High
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000,1400.0,12600.0,Normal,Low
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000,8250.0,46750.0,Fast,Medium
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0,3300.0,Slow,High
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000,6500.0,58500.0,Fast,Low

In [267]:
df['Customer_Satisfaction'] = df['Rating'].apply(
    lambda x: 'Satisfied' if x>=4 else 'Unsatisfied'
)
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category,Customer_Satisfaction
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000,6500.0,58500.0,Fast,Low,Satisfied
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,4,Delivered,CARD,Returning,2400,480.0,1920.0,Normal,Medium,Satisfied
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,4,Delivered,UPI,New,2500,125.0,2375.0,Fast,Low,Satisfied
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0,3825.0,Slow,Medium,Unsatisfied
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000,5500.0,49500.0,Fast,Low,Satisfied
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,3,Delivered,UPI,Returning,4400,1100.0,3300.0,Normal,High,Unsatisfied
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0,8075.0,Slow,Low,Unsatisfied
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,5,Delivered,UPI,Returning,30000,6000.0,24000.0,Fast,Medium,Satisfied
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500,1050.0,2450.0,Slow,High,Unsatisfied
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,4,Cancelled,CARD,Returning,16000,1600.0,14400.0,Fast,Low,Satisfied
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,4,Delivered,UPI,New,7000,1050.0,5950.0,Normal,Medium,Satisfied
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,3,Delivered,CARD,Returning,4000,200.0,3800.0,Normal,Low,Unsatisfied
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000,13000.0,52000.0,Fast,Medium,Satisfied
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0,8100.0,Slow,Low,Unsatisfied
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,5,Delivered,CASH,New,3600,900.0,2700.0,Fast,High,Satisfied
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,4,Delivered,UPI,Returning,2500,375.0,2125.0,Normal,Medium,Satisfied
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0,7650.0,Slow,Low,Unsatisfied
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,4,Delivered,UPI,Returning,4400,880.0,3520.0,Normal,Medium,Satisfied
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,5,Delivered,CARD,New,55000,2750.0,52250.0,Fast,Low,Satisfied
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,3,Cancelled,CASH,Returning,8000,2400.0,5600.0,Fast,High,Unsatisfied
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000,6500.0,58500.0,Normal,Low,Satisfied
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0,6000.0,Slow,High,Unsatisfied
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,4,Delivered,UPI,Returning,5000,750.0,4250.0,Fast,Medium,Satisfied
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500,425.0,8075.0,Slow,Low,Unsatisfied
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,5,Delivered,CARD,Returning,30000,6000.0,24000.0,Fast,Medium,Satisfied
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0,2450.0,Slow,High,Unsatisfied
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,4,Delivered,CARD,Returning,14000,1400.0,12600.0,Normal,Low,Satisfied
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,5,Delivered,UPI,New,55000,8250.0,46750.0,Fast,Medium,Satisfied
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0,3300.0,Slow,High,Unsatisfied
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000,6500.0,58500.0,Fast,Low,Satisfied

In [268]:
df['Order_Date'].dt.month_name()

0      January
1      January
2      January
3      January
4      January
5      January
6      January
7      January
8      January
9      January
10     January
11     January
12    February
13    February
14    February
15    February
16    February
17    February
18    February
19    February
20    February
21    February
22    February
23    February
24       March
25       March
26       March
27       March
28       March
29       March
Name: Order_Date, dtype: object

In [269]:
df['Order_Date'].dt.year

0     2026
1     2026
2     2026
3     2026
4     2026
5     2026
6     2026
7     2026
8     2026
9     2026
10    2026
11    2026
12    2026
13    2026
14    2026
15    2026
16    2026
17    2026
18    2026
19    2026
20    2026
21    2026
22    2026
23    2026
24    2026
25    2026
26    2026
27    2026
28    2026
29    2026
Name: Order_Date, dtype: int32

In [270]:
df['Order_Date'].dt.day_name()

0        Monday
1     Wednesday
2      Thursday
3      Saturday
4        Monday
5     Wednesday
6      Thursday
7        Sunday
8       Tuesday
9      Thursday
10       Sunday
11      Tuesday
12       Sunday
13      Tuesday
14     Thursday
15     Saturday
16      Tuesday
17     Thursday
18       Sunday
19    Wednesday
20       Friday
21       Sunday
22    Wednesday
23       Friday
24       Sunday
25      Tuesday
26     Thursday
27     Saturday
28      Tuesday
29     Thursday
Name: Order_Date, dtype: object

In [271]:
df['Order_ID'].count()

np.int64(30)

In [272]:
df['Quantity'].sum()

np.int64(41)

In [273]:
df['Order_Value'].sum()

np.int64(617200)

In [274]:
df['Discount_Amount'].sum()

np.float64(80735.0)

In [275]:
df['Final_Order_Value'].sum()

np.float64(536465.0)

In [276]:
df['Order_Value'].mean()

np.float64(20573.333333333332)

In [277]:
df['Final_Order_Value'].mean()

np.float64(17882.166666666668)

In [278]:
df['Order_Value'].max()

65000

In [279]:
df['Order_Value'].min()

2400

In [280]:
df['Final_Order_Value'].max()

58500.0

In [281]:
df['Final_Order_Value'].min()

1920.0

In [282]:
df.sort_values(by='Order_Value',ascending=False).head(5)

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category,Customer_Satisfaction
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,5,Delivered,UPI,New,65000,6500.0,58500.0,Fast,Low,Satisfied
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,5,Delivered,UPI,New,65000,13000.0,52000.0,Fast,Medium,Satisfied
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,5,Delivered,CARD,New,65000,6500.0,58500.0,Fast,Low,Satisfied
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,5,Delivered,UPI,Returning,65000,6500.0,58500.0,Normal,Low,Satisfied
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,5,Delivered,CARD,New,55000,5500.0,49500.0,Fast,Low,Satisfied

In [283]:
df.groupby('Product')['Quantity'].sum()

Product
Air Fryer     3
Headphones    4
Jacket        2
Jeans         6
Laptop        4
Microwave     3
Mixer         3
Shoes         3
Smartphone    3
Smartwatch    3
T-Shirt       5
Tablet        2
Name: Quantity, dtype: int64

In [284]:
df.groupby('Product')['Order_Value'].sum()

Product
Air Fryer      21000
Headphones     10000
Jacket          7000
Jeans          13200
Laptop        260000
Microwave      25500
Mixer          13500
Shoes          12000
Smartphone    165000
Smartwatch     24000
T-Shirt         6000
Tablet         60000
Name: Order_Value, dtype: int64

In [285]:
df.groupby('Product')['Order_Value'].mean().round(1)

Product
Air Fryer     10500.0
Headphones     3333.3
Jacket         3500.0
Jeans          4400.0
Laptop        65000.0
Microwave      8500.0
Mixer          6750.0
Shoes          6000.0
Smartphone    55000.0
Smartwatch    12000.0
T-Shirt        3000.0
Tablet        30000.0
Name: Order_Value, dtype: float64

In [286]:
df.groupby('Product')['Rating'].mean().round(1)

Product
Air Fryer     4.0
Headphones    4.0
Jacket        2.5
Jeans         3.3
Laptop        5.0
Microwave     2.7
Mixer         2.0
Shoes         2.5
Smartphone    5.0
Smartwatch    3.5
T-Shirt       4.5
Tablet        5.0
Name: Rating, dtype: float64

In [287]:
df.groupby('Product')['Order_ID'].count()

Product
Air Fryer     2
Headphones    3
Jacket        2
Jeans         3
Laptop        4
Microwave     3
Mixer         2
Shoes         2
Smartphone    3
Smartwatch    2
T-Shirt       2
Tablet        2
Name: Order_ID, dtype: int64

In [288]:
df.groupby('Product')['Final_Order_Value'].sum().head(1)

Product
Air Fryer    18550.0
Name: Final_Order_Value, dtype: float64

In [289]:
df.groupby('Product')['Final_Order_Value'].sum().tail(1)

Product
Tablet    48000.0
Name: Final_Order_Value, dtype: float64

In [290]:
df.groupby('Product')['Rating'].mean().head(1)

Product
Air Fryer    4.0
Name: Rating, dtype: float64

In [291]:
ratings = df.groupby('Product')['Rating'].mean().round(1)
ratings[ratings<4]

Product
Jacket        2.5
Jeans         3.3
Microwave     2.7
Mixer         2.0
Shoes         2.5
Smartwatch    3.5
Name: Rating, dtype: float64

In [292]:
values = df.groupby('Product')['Final_Order_Value'].sum().sort_values(ascending=False)
values[values>100000]

Product
Laptop        227500.0
Smartphone    148500.0
Name: Final_Order_Value, dtype: float64

In [293]:
df.groupby('Product')['Final_Order_Value'].sum().sort_values(ascending=False)

Product
Laptop        227500.0
Smartphone    148500.0
Tablet         48000.0
Microwave      23800.0
Smartwatch     20000.0
Air Fryer      18550.0
Mixer          11925.0
Jeans          10120.0
Shoes           9800.0
Headphones      8750.0
Jacket          4900.0
T-Shirt         4620.0
Name: Final_Order_Value, dtype: float64

In [294]:
df.groupby('Product_Category')['Final_Order_Value'].sum()

Product_Category
Clothing            29440.0
Electronics        452750.0
Home Appliances     54275.0
Name: Final_Order_Value, dtype: float64

In [295]:
df.groupby('Product_Category')['Quantity'].sum()

Product_Category
Clothing           16
Electronics        16
Home Appliances     9
Name: Quantity, dtype: int64

In [296]:
df.groupby('Product_Category')['Order_Value'].mean().round(2)

Product_Category
Clothing            4244.44
Electronics        37071.43
Home Appliances     8571.43
Name: Order_Value, dtype: float64

In [297]:
df.groupby('Product_Category')['Discount'].mean().round(2)

Product_Category
Clothing           22.78
Electronics        13.93
Home Appliances    10.00
Name: Discount, dtype: float64

In [298]:
df.groupby('Product_Category')['Rating'].mean().round(1)

Product_Category
Clothing           3.2
Electronics        4.6
Home Appliances    2.9
Name: Rating, dtype: float64

In [299]:
df.groupby('Product_Category')['Order_ID'].count()

Product_Category
Clothing            9
Electronics        14
Home Appliances     7
Name: Order_ID, dtype: int64

In [300]:
df.groupby('Product_Category')['Final_Order_Value'].sum().sort_values(ascending=False).head(1)

Product_Category
Electronics    452750.0
Name: Final_Order_Value, dtype: float64

In [301]:
ratings = df.groupby('Product_Category')['Rating'].mean().round(1)
ratings[ratings<4]

Product_Category
Clothing           3.2
Home Appliances    2.9
Name: Rating, dtype: float64

In [302]:
rates = df.groupby('Product_Category')['Final_Order_Value'].sum().sort_values(ascending=False)
rates[rates>200000]

Product_Category
Electronics    452750.0
Name: Final_Order_Value, dtype: float64

In [303]:
df.groupby('Customer')['Order_ID'].count()

Customer
Amit      2
Anjali    1
Anu       1
Arun      2
Asha      1
Divya     1
Isha      1
Kiran     2
Meera     1
Neha      2
Nikhil    1
Pooja     2
Priya     2
Rahul     2
Rakesh    1
Rohit     2
Sanjay    1
Sneha     2
Varun     1
Vikram    2
Name: Order_ID, dtype: int64

In [304]:
df.groupby('Customer')['Final_Order_Value'].sum()

Customer
Amit       64450.0
Anjali      3300.0
Anu         5600.0
Arun      117000.0
Asha        3520.0
Divya       8100.0
Isha        2125.0
Kiran      10525.0
Meera       3800.0
Neha       36600.0
Nikhil      2700.0
Pooja      17700.0
Priya       7920.0
Rahul       6625.0
Rakesh     52250.0
Rohit      49200.0
Sanjay     52000.0
Sneha      11900.0
Varun       7650.0
Vikram     73500.0
Name: Final_Order_Value, dtype: float64

In [305]:
df.groupby('Customer')['Order_Value'].mean().round(1)

Customer
Amit      36000.0
Anjali     4400.0
Anu        8000.0
Arun      65000.0
Asha       4400.0
Divya      9000.0
Isha       2500.0
Kiran      6000.0
Meera      4000.0
Neha      22000.0
Nikhil     3600.0
Pooja     10200.0
Priya      5200.0
Rahul      3750.0
Rakesh    55000.0
Rohit     29250.0
Sanjay    65000.0
Sneha      6500.0
Varun      8500.0
Vikram    42500.0
Name: Order_Value, dtype: float64

In [306]:
df.groupby('Customer')['Quantity'].sum()

Customer
Amit      2
Anjali    2
Anu       1
Arun      2
Asha      2
Divya     2
Isha      1
Kiran     2
Meera     1
Neha      3
Nikhil    3
Pooja     4
Priya     4
Rahul     3
Rakesh    1
Rohit     2
Sanjay    1
Sneha     2
Varun     1
Vikram    2
Name: Quantity, dtype: int64

In [307]:
df.groupby('Customer')['Rating'].mean().round(1)

Customer
Amit      4.5
Anjali    3.0
Anu       3.0
Arun      5.0
Asha      4.0
Divya     2.0
Isha      4.0
Kiran     2.0
Meera     3.0
Neha      4.5
Nikhil    5.0
Pooja     3.5
Priya     3.0
Rahul     4.0
Rakesh    5.0
Rohit     4.0
Sanjay    5.0
Sneha     2.5
Varun     3.0
Vikram    5.0
Name: Rating, dtype: float64

In [308]:
c = df.groupby('Customer')['Order_ID'].count()
c[c>1]

Customer
Amit      2
Arun      2
Kiran     2
Neha      2
Pooja     2
Priya     2
Rahul     2
Rohit     2
Sneha     2
Vikram    2
Name: Order_ID, dtype: int64

In [309]:
order = df.groupby('Customer')['Final_Order_Value'].sum().sort_values(ascending=False)
order[order>100000]

Customer
Arun    117000.0
Name: Final_Order_Value, dtype: float64

In [310]:
df.groupby('Customer')['Final_Order_Value'].sum().sort_values(ascending=False).head(1)

Customer
Arun    117000.0
Name: Final_Order_Value, dtype: float64

In [311]:
c[c==c.max()]

Customer
Amit      2
Arun      2
Kiran     2
Neha      2
Pooja     2
Priya     2
Rahul     2
Rohit     2
Sneha     2
Vikram    2
Name: Order_ID, dtype: int64

In [312]:
ra = df.groupby('Customer')['Rating'].mean().round(1)
ra[ra<4]

Customer
Anjali    3.0
Anu       3.0
Divya     2.0
Kiran     2.0
Meera     3.0
Pooja     3.5
Priya     3.0
Sneha     2.5
Varun     3.0
Name: Rating, dtype: float64

In [313]:
Custom_Summary = df.groupby('Customer').agg(
    Total_Orders = ('Order_ID','count'),
    Total_Quantity = ('Quantity','sum'),
    Total_Order_Value = ('Order_Value','sum'),
    Average_Order_Value = ('Order_Value','mean'),
    Total_Discount_Amount = ('Discount_Amount','sum'),
    Total_Spending = ('Final_Order_Value','sum'),
    Average_Rating = ('Rating','mean')
)

In [314]:
Custom_Summary = Custom_Summary.sort_values('Total_Spending',ascending=False)
Custom_Summary

,Total_Orders,Total_Quantity,Total_Order_Value,Average_Order_Value,Total_Discount_Amount,Total_Spending,Average_Rating
Customer,,,,,,,
Arun,2,2,130000,65000.0,13000.0,117000.0,5.0
Vikram,2,2,85000,42500.0,11500.0,73500.0,5.0
Amit,2,2,72000,36000.0,7550.0,64450.0,4.5
Rakesh,1,1,55000,55000.0,2750.0,52250.0,5.0
Sanjay,1,1,65000,65000.0,13000.0,52000.0,5.0
Rohit,2,2,58500,29250.0,9300.0,49200.0,4.0
Neha,2,3,44000,22000.0,7400.0,36600.0,4.5
Pooja,2,4,20400,10200.0,2700.0,17700.0,3.5
Sneha,2,2,13000,6500.0,1100.0,11900.0,2.5
Kiran,2,2,12000,6000.0,1475.0,10525.0,2.0
Divya,1,2,9000,9000.0,900.0,8100.0,2.0
Priya,2,4,10400,5200.0,2480.0,7920.0,3.0
Varun,1,1,8500,8500.0,850.0,7650.0,3.0
Rahul,2,3,7500,3750.0,875.0,6625.0,4.0
Anu,1,1,8000,8000.0,2400.0,5600.0,3.0
Meera,1,1,4000,4000.0,200.0,3800.0,3.0
Asha,1,2,4400,4400.0,880.0,3520.0,4.0
Anjali,1,2,4400,4400.0,1100.0,3300.0,3.0
Nikhil,1,3,3600,3600.0,900.0,2700.0,5.0
Isha,1,1,2500,2500.0,375.0,2125.0,4.0

In [315]:
df['Customer_Type'].value_counts()['New']

np.int64(15)

In [316]:
df['Customer_Type'].value_counts()['Returning']

np.int64(15)

In [317]:
df.groupby('Customer_Type')['Final_Order_Value'].sum()

Customer_Type
New          363225.0
Returning    173240.0
Name: Final_Order_Value, dtype: float64

In [318]:
df.groupby('Customer_Type')['Order_Value'].mean().round(2)

Customer_Type
New          27573.33
Returning    13573.33
Name: Order_Value, dtype: float64

In [319]:
df.groupby('Customer_Type')['Discount'].mean().round(2)

Customer_Type
New          14.67
Returning    16.67
Name: Discount, dtype: float64

In [320]:
df.groupby('Customer_Type')['Final_Order_Value'].sum()

Customer_Type
New          363225.0
Returning    173240.0
Name: Final_Order_Value, dtype: float64

In [321]:
df.groupby('City')['Order_ID'].count()

City
Bangalore    8
Chennai      6
Delhi        6
Hyderabad    4
Mumbai       6
Name: Order_ID, dtype: int64

In [322]:
df.groupby('City')['Final_Order_Value'].sum()

City
Bangalore    311800.0
Chennai       37900.0
Delhi         98745.0
Hyderabad     63650.0
Mumbai        24370.0
Name: Final_Order_Value, dtype: float64

In [323]:
df.groupby('Customer_Type')['Order_Value'].mean().round(1)

Customer_Type
New          27573.3
Returning    13573.3
Name: Order_Value, dtype: float64

In [324]:
df.groupby('City')['Delivery_Days'].mean().round(1)

City
Bangalore    3.6
Chennai      4.3
Delhi        3.7
Hyderabad    5.0
Mumbai       5.3
Name: Delivery_Days, dtype: float64

In [325]:
df.groupby('City')['Rating'].mean().round(1)

City
Bangalore    4.4
Chennai      3.3
Delhi        4.3
Hyderabad    3.8
Mumbai       2.8
Name: Rating, dtype: float64

In [326]:
city_stats = df.groupby('City').agg(
    Total_Orders=('Order_Status', 'count'),
    Cancelled_Orders=('Order_Status', lambda x: x.eq('Cancelled').sum())
)

city_stats['Cancellation_Rate'] = (
    city_stats['Cancelled_Orders'] / city_stats['Total_Orders']
) * 100

print(city_stats)

           Total_Orders  Cancelled_Orders  Cancellation_Rate
City
Bangalore             8                 1          12.500000
Chennai               6                 4          66.666667
Delhi                 6                 0           0.000000
Hyderabad             4                 1          25.000000
Mumbai                6                 3          50.000000

In [327]:
df.groupby('City')['Final_Order_Value'].sum().head(1)

City
Bangalore    311800.0
Name: Final_Order_Value, dtype: float64

In [328]:
df.groupby('City')['Order_Value'].mean().sort_values(ascending=False).head(1)

City
Bangalore    43437.5
Name: Order_Value, dtype: float64

In [329]:
df.groupby('City')['Rating'].mean().round(1).sort_values(ascending=False).head(1)

City
Bangalore    4.4
Name: Rating, dtype: float64

In [330]:
city_stats[city_stats['Cancellation_Rate']>20]

           Total_Orders  Cancelled_Orders  Cancellation_Rate
City
Chennai               6                 4          66.666667
Hyderabad             4                 1          25.000000
Mumbai                6                 3          50.000000

In [331]:
df['Delivery_Performance'].value_counts()

Delivery_Performance
Fast      13
Slow       9
Normal     8
Name: count, dtype: int64

In [332]:
(df['Delivery_Performance'].value_counts(normalize=True)*100).round(1)

Delivery_Performance
Fast      43.3
Slow      30.0
Normal    26.7
Name: proportion, dtype: float64

In [333]:
df.groupby('Delivery_Performance')['Rating'].mean().round(1)

Delivery_Performance
Fast      4.6
Normal    3.9
Slow      2.4
Name: Rating, dtype: float64

In [334]:
df[(df['Order_Status']=='Cancelled') & (df['Delivery_Days']>5)]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category,Customer_Satisfaction
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0,3825.0,Slow,Medium,Unsatisfied
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0,8075.0,Slow,Low,Unsatisfied
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0,8100.0,Slow,Low,Unsatisfied
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0,7650.0,Slow,Low,Unsatisfied
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0,6000.0,Slow,High,Unsatisfied
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0,2450.0,Slow,High,Unsatisfied
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0,3300.0,Slow,High,Unsatisfied

In [335]:
df[(df['Rating']<=3) & (df['Delivery_Days']>5)]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,Rating,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category,Customer_Satisfaction
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,2,Cancelled,CASH,Returning,4500,675.0,3825.0,Slow,Medium,Unsatisfied
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,2,Cancelled,CARD,New,8500,425.0,8075.0,Slow,Low,Unsatisfied
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,3,Delivered,CASH,New,3500,1050.0,2450.0,Slow,High,Unsatisfied
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,2,Cancelled,CARD,Returning,9000,900.0,8100.0,Slow,Low,Unsatisfied
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,3,Cancelled,CARD,New,8500,850.0,7650.0,Slow,Low,Unsatisfied
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,2,Cancelled,CARD,New,8000,2000.0,6000.0,Slow,High,Unsatisfied
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,3,Delivered,CASH,New,8500,425.0,8075.0,Slow,Low,Unsatisfied
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,2,Cancelled,UPI,New,3500,1050.0,2450.0,Slow,High,Unsatisfied
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,3,Cancelled,CASH,Returning,4400,1100.0,3300.0,Slow,High,Unsatisfied

In [336]:
cancel_stats = df.groupby('Delivery_Performance').agg(
    Total_Orders=('Order_Status', 'count'),
    Cancelled_Orders=('Order_Status', lambda x: x.eq('Cancelled').sum())
)

cancel_stats['Cancellation_Rate'] = ((
    cancel_stats['Cancelled_Orders'] / cancel_stats['Total_Orders']
) * 100).round(1)
print(cancel_stats)

                      Total_Orders  Cancelled_Orders  Cancellation_Rate
Delivery_Performance
Fast                            13                 2               15.4
Normal                           8                 0                0.0
Slow                             9                 7               77.8

In [337]:
df['Discount_Type'] = df['Discount'].apply(
    lambda x: 'Discount >= 20%' if x>=20 else 'Discount < 20%'
)
df

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,...,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category,Customer_Satisfaction,Discount_Type
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,...,Delivered,UPI,New,65000,6500.0,58500.0,Fast,Low,Satisfied,Discount < 20%
1,1002,Priya,Mumbai,Clothing,T-Shirt,2,1200,20,2026-01-07,4,...,Delivered,CARD,Returning,2400,480.0,1920.0,Normal,Medium,Satisfied,Discount >= 20%
2,1003,Rahul,Delhi,Electronics,Headphones,1,2500,5,2026-01-08,3,...,Delivered,UPI,New,2500,125.0,2375.0,Fast,Low,Satisfied,Discount < 20%
3,1004,Sneha,Chennai,Home Appliances,Mixer,1,4500,15,2026-01-10,6,...,Cancelled,CASH,Returning,4500,675.0,3825.0,Slow,Medium,Unsatisfied,Discount < 20%
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,...,Delivered,CARD,New,55000,5500.0,49500.0,Fast,Low,Satisfied,Discount < 20%
5,1006,Anjali,Hyderabad,Clothing,Jeans,2,2200,25,2026-01-14,5,...,Delivered,UPI,Returning,4400,1100.0,3300.0,Normal,High,Unsatisfied,Discount >= 20%
6,1007,Kiran,Mumbai,Home Appliances,Microwave,1,8500,5,2026-01-15,7,...,Cancelled,CARD,New,8500,425.0,8075.0,Slow,Low,Unsatisfied,Discount < 20%
7,1008,Neha,Delhi,Electronics,Tablet,1,30000,20,2026-01-18,3,...,Delivered,UPI,Returning,30000,6000.0,24000.0,Fast,Medium,Satisfied,Discount >= 20%
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,...,Delivered,CASH,New,3500,1050.0,2450.0,Slow,High,Unsatisfied,Discount >= 20%
9,1010,Pooja,Chennai,Electronics,Smartwatch,2,8000,10,2026-01-22,2,...,Cancelled,CARD,Returning,16000,1600.0,14400.0,Fast,Low,Satisfied,Discount < 20%
10,1011,Amit,Hyderabad,Home Appliances,Air Fryer,1,7000,15,2026-01-25,5,...,Delivered,UPI,New,7000,1050.0,5950.0,Normal,Medium,Satisfied,Discount < 20%
11,1012,Meera,Mumbai,Clothing,Shoes,1,4000,5,2026-01-27,4,...,Delivered,CARD,Returning,4000,200.0,3800.0,Normal,Low,Unsatisfied,Discount < 20%
12,1013,Sanjay,Delhi,Electronics,Laptop,1,65000,20,2026-02-01,3,...,Delivered,UPI,New,65000,13000.0,52000.0,Fast,Medium,Satisfied,Discount >= 20%
13,1014,Divya,Bangalore,Home Appliances,Mixer,2,4500,10,2026-02-03,6,...,Cancelled,CARD,Returning,9000,900.0,8100.0,Slow,Low,Unsatisfied,Discount < 20%
14,1015,Nikhil,Chennai,Clothing,T-Shirt,3,1200,25,2026-02-05,2,...,Delivered,CASH,New,3600,900.0,2700.0,Fast,High,Satisfied,Discount >= 20%
15,1016,Isha,Mumbai,Electronics,Headphones,1,2500,15,2026-02-07,4,...,Delivered,UPI,Returning,2500,375.0,2125.0,Normal,Medium,Satisfied,Discount < 20%
16,1017,Varun,Hyderabad,Home Appliances,Microwave,1,8500,10,2026-02-10,7,...,Cancelled,CARD,New,8500,850.0,7650.0,Slow,Low,Unsatisfied,Discount < 20%
17,1018,Asha,Delhi,Clothing,Jeans,2,2200,20,2026-02-12,5,...,Delivered,UPI,Returning,4400,880.0,3520.0,Normal,Medium,Satisfied,Discount >= 20%
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,...,Delivered,CARD,New,55000,2750.0,52250.0,Fast,Low,Satisfied,Discount < 20%
19,1020,Anu,Chennai,Electronics,Smartwatch,1,8000,30,2026-02-18,2,...,Cancelled,CASH,Returning,8000,2400.0,5600.0,Fast,High,Unsatisfied,Discount >= 20%
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,...,Delivered,UPI,Returning,65000,6500.0,58500.0,Normal,Low,Satisfied,Discount < 20%
21,1022,Priya,Mumbai,Clothing,Shoes,2,4000,25,2026-02-22,6,...,Cancelled,CARD,New,8000,2000.0,6000.0,Slow,High,Unsatisfied,Discount >= 20%
22,1023,Rahul,Delhi,Electronics,Headphones,2,2500,15,2026-02-25,3,...,Delivered,UPI,Returning,5000,750.0,4250.0,Fast,Medium,Satisfied,Discount < 20%
23,1024,Sneha,Chennai,Home Appliances,Microwave,1,8500,5,2026-02-27,8,...,Delivered,CASH,New,8500,425.0,8075.0,Slow,Low,Unsatisfied,Discount < 20%
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,...,Delivered,CARD,Returning,30000,6000.0,24000.0,Fast,Medium,Satisfied,Discount >= 20%
25,1026,Kiran,Mumbai,Clothing,Jacket,1,3500,30,2026-03-03,7,...,Cancelled,UPI,New,3500,1050.0,2450.0,Slow,High,Unsatisfied,Discount >= 20%
26,1027,Neha,Delhi,Home Appliances,Air Fryer,2,7000,10,2026-03-05,5,...,Delivered,CARD,Returning,14000,1400.0,12600.0,Normal,Low,Satisfied,Discount < 20%
27,1028,Rohit,Hyderabad,Electronics,Smartphone,1,55000,15,2026-03-07,3,...,Delivered,UPI,New,55000,8250.0,46750.0,Fast,Medium,Satisfied,Discount < 20%
28,1029,Pooja,Chennai,Clothing,Jeans,2,2200,25,2026-03-10,6,...,Cancelled,CASH,Returning,4400,1100.0,3300.0,Slow,High,Unsatisfied,Discount >= 20%
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,...,Delivered,CARD,New,65000,6500.0,58500.0,Fast,Low,Satisfied,Discount < 20%

In [338]:
df.groupby('Discount_Type')['Final_Order_Value'].mean().round(1)

Discount_Type
Discount < 20%     22512.5
Discount >= 20%    10936.7
Name: Final_Order_Value, dtype: float64

In [339]:
df.groupby('Discount_Type')['Final_Order_Value'].sum().round(1)

Discount_Type
Discount < 20%     405225.0
Discount >= 20%    131240.0
Name: Final_Order_Value, dtype: float64

In [340]:
catz = df.groupby('Discount_Category')['Final_Order_Value'].mean().round(1)

if(catz['High']>catz['Low']):
    print("High Discount Category")
else:
    print("Low Discount Category")

Low Discount Category

In [341]:
df['Payment_Mode'].value_counts(normalize=True)*100

Payment_Mode
UPI     40.0
CARD    40.0
CASH    20.0
Name: proportion, dtype: float64

In [342]:
cancelled_value = (df.groupby('Order_Status')['Final_Order_Value'].sum())['Cancelled']
total_value = df['Final_Order_Value'].sum()

print(((cancelled_value/total_value)*100).round(1))

11.1

In [343]:
df.groupby(df['Order_Date'].dt.month_name())['Order_ID'].count()

Order_Date
February    12
January     12
March        6
Name: Order_ID, dtype: int64

In [344]:
monthly_revenue = df.groupby(df['Order_Date'].dt.month_name())['Final_Order_Value'].sum()
monthly_revenue

Order_Date
February    210770.0
January     178095.0
March       147600.0
Name: Final_Order_Value, dtype: float64

In [345]:
met = df.groupby(['City','Order_ID'])['Order_Value'].sum()
met.groupby(level='City').mean().round(1)

City
Bangalore    43437.5
Chennai       7500.0
Delhi        20150.0
Hyderabad    18725.0
Mumbai        4816.7
Name: Order_Value, dtype: float64

In [346]:
mains = df.groupby('Product_Category').agg(
    cancelled = ('Order_Status',lambda x: x.eq('Cancelled').sum()),
    delivered = ('Order_Status',lambda x: x.eq('Delivered').sum()),
    total_orders = ('Order_Status','count')
)
mains['cancellations'] = ((mains['cancelled']/mains['total_orders'])*100).round(1)
mains.sort_values(by='cancellations', ascending=False,inplace=True)
mains['cancellations'].head(1)

Product_Category
Home Appliances    57.1
Name: cancellations, dtype: float64

In [347]:
combo = df.groupby('Product').agg(
    total_orders = ('Order_Status','count'),
    cancelled_orders = ('Order_Status', lambda x: x.eq('Cancelled').sum()),
    Rating=('Rating', 'mean'),
    Delivery_Time=('Delivery_Days', 'mean')
)
combo['cancellation_rate'] = ((combo['cancelled_orders']/combo['total_orders'])*100).round(1)
combo.sort_values(by='cancellation_rate', ascending=False, inplace=True)

combo['Rating'] = combo['Rating'].round(1)
combo['Delivery_Time'] = combo['Delivery_Time'].round(1)

combo['Rating_rank'] = combo['Rating'].rank(ascending=False)
combo['Delivery_Time_rank'] = combo['Delivery_Time'].rank()
combo['cancellation_rate_rank'] = combo['cancellation_rate']

combo['worst_combination_score'] = (
    combo['Rating_rank']
    + combo['Delivery_Time_rank']
    + combo['cancellation_rate_rank']
)

combo.sort_values(by='worst_combination_score', ascending=True, inplace=True)
combo.head(1)

,total_orders,cancelled_orders,Rating,Delivery_Time,cancellation_rate,Rating_rank,Delivery_Time_rank,cancellation_rate_rank,worst_combination_score
Product,,,,,,,,,
Tablet,2,0,5.0,2.5,0.0,2.0,2.0,0.0,4.0

In [348]:
total_orders = df['Order_ID'].count().round(1)
delivered_orders = df['Order_Status'].eq('Delivered').sum().round(1)
cancelled_orders = df['Order_Status'].eq('Cancelled').sum().round(1)
total_gross_order_value = df['Order_Value'].sum().round(1)
total_discount_amount = df['Discount_Amount'].sum().round(1)
total_final_revenue = df['Final_Order_Value'].sum().round(1)
average_order_value = df['Order_Value'].mean().round(1)
average_final_order_value = df['Final_Order_Value'].mean().round(1)
average_delivery_days = df['Delivery_Days'].mean().round(1)
average_rating = df['Rating'].mean().round(1)

metric_data = {
    'Total_Orders': total_orders,
    'Delivered_Orders': delivered_orders,
    'Cancelled_Orders': cancelled_orders,
    'Total_Gross_Order_Value': total_gross_order_value,
    'Total_Discount_Amount': total_discount_amount,
    'Total_Final_Revenue': total_final_revenue,
    'Average_Order_Value': average_order_value,
    'Average_Final_Order_Value': average_final_order_value,
    'Average_Delivery_Days': average_delivery_days,
    'Average_Rating': average_rating
}

metric = pd.Series(metric_data)
metric['Cancellation_Rate'] = ((metric['Cancelled_Orders'] / metric['Total_Orders']) * 100).round(1)
metric

Total_Orders                     30.0
Delivered_Orders                 21.0
Cancelled_Orders                  9.0
Total_Gross_Order_Value      617200.0
Total_Discount_Amount         80735.0
Total_Final_Revenue          536465.0
Average_Order_Value           20573.3
Average_Final_Order_Value     17882.2
Average_Delivery_Days             4.3
Average_Rating                    3.8
Cancellation_Rate                30.0
dtype: float64

In [349]:
Total_Orders = df['Order_ID'].count().round(1)
delivered_orders = df['Order_Status'].eq('Delivered').sum().round(1)
cancelled_orders = df['Order_Status'].eq('Cancelled').sum().round(1)
cancellation_rate = ((cancelled_orders / Total_Orders) * 100).round(1)
Total_Quantity = df['Quantity'].sum().round(1)
Gross_Revenue = df['Order_Value'].sum().round(1)
Total_Discount = df['Discount_Amount'].sum().round(1)
Final_Revenue = df['Final_Order_Value'].sum().round(1)
Average_Order_Value = df['Order_Value'].mean().round(1)
Average_Final_Order_Value = df['Final_Order_Value'].mean().round(1)
Average_Delivery_Days = df['Delivery_Days'].mean().round(1)

report = {
    'Product_Category': df['Product_Category'].unique(),
    'Total_Orders': Total_Orders,
    'Delivered_Orders': delivered_orders,
    'Cancelled_Orders': cancelled_orders,
    'Cancellation_Rate': cancellation_rate,
    'Total_Quantity': Total_Quantity,
    'Gross_Revenue': Gross_Revenue,
    'Total_Discount': Total_Discount,
    'Final_Revenue': Final_Revenue,
    'Average_Order_Value': Average_Order_Value,
    'Average_Final_Order_Value': Average_Final_Order_Value,
    'Average_Delivery_Days': Average_Delivery_Days
}

report_df = pd.Series(report)
report_df

Product_Category             [Electronics, Clothing, Home Appliances]
Total_Orders                                                       30
Delivered_Orders                                                   21
Cancelled_Orders                                                    9
Cancellation_Rate                                                30.0
Total_Quantity                                                     41
Gross_Revenue                                                  617200
Total_Discount                                                80735.0
Final_Revenue                                                536465.0
Average_Order_Value                                           20573.3
Average_Final_Order_Value                                     17882.2
Average_Delivery_Days                                             4.3
dtype: object

In [350]:
report = df.groupby('Product_Category').agg(
    Total_Orders=('Order_ID', 'count'),
    delivered_orders = ('Order_Status', lambda x: x.eq('Delivered').sum()),
    cancelled_orders = ('Order_Status', lambda x: x.eq('Cancelled').sum()),
    cancellation_rate = ('Order_Status', lambda x: ((x.eq('Cancelled').sum() / x.count()) * 100)),
    Total_Quantity=('Quantity', 'sum'),
    Gross_Revenue=('Order_Value', 'sum'),
    Total_Discount=('Discount_Amount', 'sum'),
    Final_Revenue=('Final_Order_Value', 'sum'),
    Average_Order_Value=('Order_Value', 'mean'),
    Average_Final_Order_Value=('Final_Order_Value', 'mean'),
    Average_Delivery_Days=('Delivery_Days', 'mean')
).round(1)

report.sort_values(by='cancellation_rate', ascending=False, inplace=True)
report

,Total_Orders,delivered_orders,cancelled_orders,cancellation_rate,Total_Quantity,Gross_Revenue,Total_Discount,Final_Revenue,Average_Order_Value,Average_Final_Order_Value,Average_Delivery_Days
Product_Category,,,,,,,,,,,
Home Appliances,7,3,4,57.1,9,60000,5725.0,54275.0,8571.4,7753.6,6.3
Clothing,9,6,3,33.3,16,38200,8760.0,29440.0,4244.4,3271.1,5.2
Electronics,14,12,2,14.3,16,519000,66250.0,452750.0,37071.4,32339.3,2.7

In [351]:
df.loc[(df['City']=='Bangalore') & (df['Order_Status']=='Delivered')]

,Order_ID,Customer,City,Product_Category,Product,Quantity,Unit_Price,Discount,Order_Date,Delivery_Days,...,Order_Status,Payment_Mode,Customer_Type,Order_Value,Discount_Amount,Final_Order_Value,Delivery_Performance,Discount_Category,Customer_Satisfaction,Discount_Type
0,1001,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-01-05,2,...,Delivered,UPI,New,65000,6500.0,58500.0,Fast,Low,Satisfied,Discount < 20%
4,1005,Vikram,Bangalore,Electronics,Smartphone,1,55000,10,2026-01-12,2,...,Delivered,CARD,New,55000,5500.0,49500.0,Fast,Low,Satisfied,Discount < 20%
8,1009,Rohit,Bangalore,Clothing,Jacket,1,3500,30,2026-01-20,8,...,Delivered,CASH,New,3500,1050.0,2450.0,Slow,High,Unsatisfied,Discount >= 20%
18,1019,Rakesh,Bangalore,Electronics,Smartphone,1,55000,5,2026-02-15,3,...,Delivered,CARD,New,55000,2750.0,52250.0,Fast,Low,Satisfied,Discount < 20%
20,1021,Arun,Bangalore,Electronics,Laptop,1,65000,10,2026-02-20,4,...,Delivered,UPI,Returning,65000,6500.0,58500.0,Normal,Low,Satisfied,Discount < 20%
24,1025,Vikram,Bangalore,Electronics,Tablet,1,30000,20,2026-03-01,2,...,Delivered,CARD,Returning,30000,6000.0,24000.0,Fast,Medium,Satisfied,Discount >= 20%
29,1030,Amit,Bangalore,Electronics,Laptop,1,65000,10,2026-03-12,2,...,Delivered,CARD,New,65000,6500.0,58500.0,Fast,Low,Satisfied,Discount < 20%

In [352]:
df.iloc[5:16,2:7]

         City Product_Category     Product  Quantity  Unit_Price
5   Hyderabad         Clothing       Jeans         2        2200
6      Mumbai  Home Appliances   Microwave         1        8500
7       Delhi      Electronics      Tablet         1       30000
8   Bangalore         Clothing      Jacket         1        3500
9     Chennai      Electronics  Smartwatch         2        8000
10  Hyderabad  Home Appliances   Air Fryer         1        7000
11     Mumbai         Clothing       Shoes         1        4000
12      Delhi      Electronics      Laptop         1       65000
13  Bangalore  Home Appliances       Mixer         2        4500
14    Chennai         Clothing     T-Shirt         3        1200
15     Mumbai      Electronics  Headphones         1        2500

In [353]:
asin = df.groupby('Product')['Final_Order_Value'].sum()
asin.idxmax()

'Laptop'

In [354]:
df.groupby('Customer')['Product'].nunique()

Customer
Amit      2
Anjali    1
Anu       1
Arun      1
Asha      1
Divya     1
Isha      1
Kiran     2
Meera     1
Neha      2
Nikhil    1
Pooja     2
Priya     2
Rahul     1
Rakesh    1
Rohit     2
Sanjay    1
Sneha     2
Varun     1
Vikram    2
Name: Product, dtype: int64

In [355]:
df['Order_Size'] = df['Final_Order_Value'].apply(
    lambda x: 'Small' if x<5000 else 'Medium' if x>5000 and x<20000 else 'Large'
)
df['Order_Size']

0      Large
1      Small
2      Small
3      Small
4      Large
5      Small
6     Medium
7      Large
8      Small
9     Medium
10    Medium
11     Small
12     Large
13    Medium
14     Small
15     Small
16    Medium
17     Small
18     Large
19    Medium
20     Large
21    Medium
22     Small
23    Medium
24     Large
25     Small
26    Medium
27     Large
28     Small
29     Large
Name: Order_Size, dtype: object

In [368]:
Total_Revenue = df['Final_Order_Value'].sum().round(1)
Average_Order_Value = df['Order_Value'].mean().round(1)
Top_Product = df.groupby('Product')['Order_Value'].sum().round(1).idxmax()
Top_Category = df.groupby('Product_Category')['Order_Value'].sum().round(1).idxmax()
Total_Customers = df['Customer'].nunique()
Top_Customer = df.groupby('Customer')['Order_Value'].sum().round(1).idxmax()
New_Vs_Old = df['Customer_Type'].value_counts()
Cancellation_Rate = ((df[df['Order_Status']=='Cancelled']['Order_ID'].count()/df['Order_ID'].count())*100).round(1)
Average_Delivery_Time = df['Delivery_Days'].mean().round(1)
Delivery_Performance_Distribution = df['Delivery_Performance'].value_counts(normalize=True)*100
Average_Rating = df['Rating'].mean().round(1)
Top_Rated_Product = df.groupby('Product')['Rating'].mean().round(1).idxmax()
Lowest_Rated_Product = df.groupby('Product')['Rating'].mean().round(1).idxmin()
Top_City = df.groupby('City')['Order_Value'].sum().round(1).idxmax()
Low_Performing_City = df.groupby('City')['Order_Value'].sum().round(1).idxmin()
Total_Discount = df['Discount_Amount'].sum().round(1)
Average_Discount = df['Discount'].mean().round(1)
High_Discount_Revenue = df.loc[df['Discount_Type']=='High','Final_Order_Value'].sum().round(1)

In [375]:
Product_Report = df.groupby('Product').agg(
    Total_Orders=('Order_ID', 'count'),
    Revenue=('Final_Order_Value', 'sum'),
    Avg_Rating=('Rating', 'mean'),
    Avg_Delivery_Time=('Delivery_Days', 'mean')
).round(1)
Prodcut_Report = Product_Report.sort_values(by='Revenue', ascending=False)
Prodcut_Report

            Total_Orders   Revenue  Avg_Rating  Avg_Delivery_Time
Product
Laptop                 4  227500.0         5.0                2.8
Smartphone             3  148500.0         5.0                2.7
Tablet                 2   48000.0         5.0                2.5
Microwave              3   23800.0         2.7                7.3
Smartwatch             2   20000.0         3.5                2.0
Air Fryer              2   18550.0         4.0                5.0
Mixer                  2   11925.0         2.0                6.0
Jeans                  3   10120.0         3.3                5.3
Shoes                  2    9800.0         2.5                5.0
Headphones             3    8750.0         4.0                3.3
Jacket                 2    4900.0         2.5                7.5
T-Shirt                2    4620.0         4.5                3.0

In [376]:
city_report = df.groupby('City').agg(
    Total_Orders=('Order_ID', 'count'),
    Revenue=('Final_Order_Value', 'sum'),
    Avg_Order_Value=('Final_Order_Value', 'mean'),
    Avg_Delivery_Time=('Delivery_Days', 'mean')
).round(1)
city_report = city_report.sort_values(by='Revenue', ascending=False)
city_report

           Total_Orders   Revenue  Avg_Order_Value  Avg_Delivery_Time
City
Bangalore             8  311800.0          38975.0                3.6
Delhi                 6   98745.0          16457.5                3.7
Hyderabad             4   63650.0          15912.5                5.0
Chennai               6   37900.0           6316.7                4.3
Mumbai                6   24370.0           4061.7                5.3

In [378]:
customer_report = df.groupby('Customer').agg(
    Total_Orders=('Order_ID', 'count'),
    Total_Spending=('Final_Order_Value', 'sum'),
    Avg_Order_Value=('Final_Order_Value', 'mean'),
    Avg_Rating=('Rating', 'mean')
).round(1)
customer_report = customer_report.sort_values(by='Total_Spending',ascending=False)
customer_report

          Total_Orders  Total_Spending  Avg_Order_Value  Avg_Rating
Customer
Arun                 2        117000.0          58500.0         5.0
Vikram               2         73500.0          36750.0         5.0
Amit                 2         64450.0          32225.0         4.5
Rakesh               1         52250.0          52250.0         5.0
Sanjay               1         52000.0          52000.0         5.0
Rohit                2         49200.0          24600.0         4.0
Neha                 2         36600.0          18300.0         4.5
Pooja                2         17700.0           8850.0         3.5
Sneha                2         11900.0           5950.0         2.5
Kiran                2         10525.0           5262.5         2.0
Divya                1          8100.0           8100.0         2.0
Priya                2          7920.0           3960.0         3.0
Varun                1          7650.0           7650.0         3.0
Rahul                2          6625.0           3312.5         4.0
Anu                  1          5600.0           5600.0         3.0
Meera                1          3800.0           3800.0         3.0
Asha                 1          3520.0           3520.0         4.0
Anjali               1          3300.0           3300.0         3.0
Nikhil               1          2700.0           2700.0         5.0
Isha                 1          2125.0           2125.0         4.0